services:
  games:
    image: 'bitnami/postgresql'
    container_name: games
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - ./db:/var/lib/postgresql
    environment:
      - POSTGRESQL_USERNAME=${POSTGRES_USERNAME}
      - POSTGRESQL_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRESQL_DATABASE=${POSTGRES_DATABASE}
    networks:
      - games-nather
  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "8080:8080"  # Porta padrão do Adminer
    depends_on:
      - games
    networks:
      - games-nather

volumes:
  db:

networks:
  games-nather:
    driver: bridge